# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            'HayNow'
tagline:          'HayNow Documentation'
description:      'Open sourced alerting tool by Ocado Technology'
url:              http://heynow-io.github.io

include: ['_pages']


github:           https://github.com/heynow-io
slack:            https://heynow-io.slack.com